
[client]

	#Properties relating to controls
	[client.controls]
		#A value to multiple the mouse sensitivity by when aiming down weapon sights. Go to (Options > Controls > Mouse Settings > ADS Sensitivity) in game to change this!
		#Range: 0.0 ~ 1.0
		aimDownSightSensitivity = 0.75

	#Control sounds triggered by guns
	[client.sounds]
		#If true, a sound will play when you successfully hit a headshot on a entity with a gun
		playSoundWhenHeadshot = true
		#The sound to play when a headshot occurs
		headshotSound = "minecraft:entity.arrow.hit_player"
		#If true, a sound will play when you successfully hit a critical on a entity with a gun
		playSoundWhenCritical = true
		#The sound to play when a critical occurs
		criticalSound = "minecraft:entity.arrow.hit_player"

	#Configuration for display related options
	[client.display]
		#The custom crosshair to use for weapons. Go to (Options > Controls > Mouse Settings > Crosshair) in game to change this!
		crosshair = "minecraft:default"
		#If true, uses the old animation poses for weapons. This is only for nostalgic reasons and not recommended to switch back.
		oldAnimations = false

	#Properties relating to particles
	[client.particle]
		#The maximum duration in ticks before bullet holes will disappear
		#Range: > 0
		bulletHoleLifeMax = 200
		#The minimum duration in ticks before bullet holes will disappear
		#Range: > 0
		bulletHoleLifeMin = 150
		#The percentage of the maximum life that must pass before particles begin fading away. 0 makes the particles always fade and 1 removes facing completely
		#Range: 0.0 ~ 1.0
		bulletHoleFadeThreshold = 0.98
		#If true, blood will will spawn from entities that are hit from a projectile
		enableBlood = false

